// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVmuedYPK6vce1GEGth3qIjwOi8SiDZRU',
    appId: '1:214483418020:web:e6eb2a544bcb5680189f31',
    messagingSenderId: '214483418020',
    projectId: 'salahiyati-d110f',
    authDomain: 'salahiyati-d110f.firebaseapp.com',
    storageBucket: 'salahiyati-d110f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1DjXHbbfgGC3uo0D6qQ01vPtus_WNkrc',
    appId: '1:214483418020:android:7bb4fc73f31f5afd189f31',
    messagingSenderId: '214483418020',
    projectId: 'salahiyati-d110f',
    storageBucket: 'salahiyati-d110f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOYEM3w-xnrOHEsbTa9Bumr_-7o5WaAvs',
    appId: '1:214483418020:ios:fb0d7f998ed6615e189f31',
    messagingSenderId: '214483418020',
    projectId: 'salahiyati-d110f',
    storageBucket: 'salahiyati-d110f.firebasestorage.app',
    iosBundleId: 'com.example.expiryGuard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOYEM3w-xnrOHEsbTa9Bumr_-7o5WaAvs',
    appId: '1:214483418020:ios:fb0d7f998ed6615e189f31',
    messagingSenderId: '214483418020',
    projectId: 'salahiyati-d110f',
    storageBucket: 'salahiyati-d110f.firebasestorage.app',
    iosBundleId: 'com.example.expiryGuard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVmuedYPK6vce1GEGth3qIjwOi8SiDZRU',
    appId: '1:214483418020:web:e6475d75d10322ba189f31',
    messagingSenderId: '214483418020',
    projectId: 'salahiyati-d110f',
    authDomain: 'salahiyati-d110f.firebaseapp.com',
    storageBucket: 'salahiyati-d110f.firebasestorage.app',
  );
}
