// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqjwrsfPEzyyiqUQQjh5m3AkKX7lhfmlk',
    appId: '1:1025500683434:web:689d5b331d50d512bcc4d3',
    messagingSenderId: '1025500683434',
    projectId: 'salahyaty-a4d82',
    authDomain: 'salahyaty-a4d82.firebaseapp.com',
    storageBucket: 'salahyaty-a4d82.firebasestorage.app',
    measurementId: 'G-ZMFCSC4HBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDImJC5B4gAF7oBSH9IyRFA12O9ihHw_xE',
    appId: '1:1025500683434:android:a57320a4163b1e33bcc4d3',
    messagingSenderId: '1025500683434',
    projectId: 'salahyaty-a4d82',
    storageBucket: 'salahyaty-a4d82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQZ0o7vHYq0_II-Tm9YGtm8iyNO_KCtGc',
    appId: '1:1025500683434:ios:7a10894194d7dd5dbcc4d3',
    messagingSenderId: '1025500683434',
    projectId: 'salahyaty-a4d82',
    storageBucket: 'salahyaty-a4d82.firebasestorage.app',
    iosBundleId: 'com.example.expiryGuard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQZ0o7vHYq0_II-Tm9YGtm8iyNO_KCtGc',
    appId: '1:1025500683434:ios:7a10894194d7dd5dbcc4d3',
    messagingSenderId: '1025500683434',
    projectId: 'salahyaty-a4d82',
    storageBucket: 'salahyaty-a4d82.firebasestorage.app',
    iosBundleId: 'com.example.expiryGuard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqjwrsfPEzyyiqUQQjh5m3AkKX7lhfmlk',
    appId: '1:1025500683434:web:09f137919cb09996bcc4d3',
    messagingSenderId: '1025500683434',
    projectId: 'salahyaty-a4d82',
    authDomain: 'salahyaty-a4d82.firebaseapp.com',
    storageBucket: 'salahyaty-a4d82.firebasestorage.app',
    measurementId: 'G-8R7V3M8KGM',
  );
}
